# Generated by Django 2.2.4 on 2019-11-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='call_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='denomination',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
